### ISSUE TITLE
Create new record for System Scheme not show 

### ISSUE THREAD

**Issue by samhvw8** [fastschema/fastschema#75]
Hi @ngocphuongnb,

Thank you for your hard working for this project
I currently follow instruction "Web Framework 🚀" in website but got error 

Blog & Tag has create successfully but New Record Page got empty

<img width="1940" alt="Screenshot 2024-06-02 at 22 31 25" src="https://github.com/fastschema/fastschema/assets/12538214/e1b3c5f2-7d23-49c7-8134-a9ba001ac0de">

**Comment by ngocphuongnb** [comment]
@samhvw8 Thank you for reporting the issue.
I seem that all the fields of a SystemSchema were marked as a SystemField, so they were filtered out from the `New record` screen.
I am working on thi problem, please wait for a while!

**Comment by ngocphuongnb** [comment]
@samhvw8 The issue has been fixed. Please try the latest version https://github.com/fastschema/fastschema/releases/tag/v0.1.1

**Comment by ngocphuongnb** [comment]
@samhvw8 The issue has been fixed. Please try the latest version https://github.com/fastschema/fastschema/releases/tag/v0.1.2
```
go get -v -u ./...
```

**Comment by samhvw8** [comment]
Thanks for you support :D 🥳
